server:
  port: 8080

spring:
  application.name: terra-azure-relay-listener
  cache:
    cache-names: expiresAt
    caffeine.spec: maximumSize=100,expireAfterAccess=3600s

listener:
  relayConnectionString:
  relayConnectionName:
  targetProperties:
    targetHost:
  requestInspectors:
#    - headersLogger
    - samChecker
  samInspectorProperties:
    samUrl:
    samResourceId:

