server:
  port: 8080

spring:
  application.name: terra-azure-relay-listener
  cache:
    cache-names: expiresAt
    caffeine.spec: maximumSize=100,expireAfterAccess=3600s

listener:
  relayConnectionString:
  relayConnectionName:
  targetProperties:
    targetHost:
    targetRoutingRules:
      -
        pathContains: "welder"
        targetHost: "http://localhost:8081"
        removeFromPath: "$hc-name/welder"
  requestInspectors:
#    - headersLogger
    - samChecker
  samInspectorProperties:
    samUrl:
    samResourceId:
    samResourceType: "controlled-application-private-workspace-resource"
  corsSupportProperties:
    preflightMethods: "OPTIONS, POST, PUT, GET, DELETE, HEAD, PATCH"
    allowHeaders: "Authorization, Content-Type, Accept, Origin,X-App-Id"
    maxAge: "1728000"
    contentSecurityPolicy: "frame-ancestors http://localhost:3000;report-uri https://terra.report-uri.com/r/d/csp/reportOnly"
