server:
  port: 8080

spring:
  application.name: terra-azure-relay-listener
  cache:
    cache-names: expiresAt
    caffeine.spec: maximumSize=100,expireAfterWrite=90s

listener:
  relayConnectionString:
  relayConnectionName:
  targetProperties:
    targetHost:
    targetRoutingRules:
      -
        pathContains: "welder"
        targetHost: "http://localhost:8081"
        removeFromPath: "$hc-name/welder"
  requestInspectors:
#    - headersLogger
    - samChecker
#    - setDateAccessed
  setDateAccessedInspectorProperties:
    serviceHost:
    workspaceId:
    callWindowInSeconds: 60
    runtimeName:

  samInspectorProperties:
    samUrl:
    samResourceId:
    samResourceType: "controlled-application-private-workspace-resource"
    samAction: "write"
  corsSupportProperties:
    preflightMethods: "OPTIONS, POST, PUT, GET, DELETE, HEAD, PATCH"
    allowHeaders: "Authorization, Content-Type, Accept, Origin,X-App-Id"
    maxAge: "1728000"
    contentSecurityPolicy: "frame-ancestors http://localhost:3000;report-uri https://terra.report-uri.com/r/d/csp/reportOnly"
    validHosts:

management:
  endpoint.health.probes.enabled: true
  health.livenessState.enabled: true
  health.readinessState.enabled: true
