server:
  port: 8080

spring:
  application.name: terra-azure-relay-listener

listener:
  relayConnectionString:
  relayConnectionName:
  targetProperties:
    targetHost:
  requestInspectors:
#    - headersLogger
    - samChecker
  samInspectorProperties:
    samUrl:
    samResourceId:

